---
  - include_vars: vars/main.yml
  - name: Initializing packages...
    apt:
      pkg: "{{ item }}"
      state: latest
    loop: "{{ PACKAGES }}"  
  
  - name: Installing konsave...
    become: yes
    become_user: "{{ansible_env.USER}}"
    command: pipx install konsave
