---
- name: Configuring wireshark...
  file:
    path: "{{target_home_dir}}/.var/app/{{APP_ID}}/config/wireshark/"
    state: absent

- name:
  file:
    path: "{{target_home_dir}}/.var/app/{{APP_ID}}/config/wireshark/"
    state: directory
- name:
  unarchive:
    src: "{{target_home_dir}}/kubuntu-build/roles/setup/applications/wireshark/files/wireshark.tar.xz"
    dest: "{{target_home_dir}}/.var/app/{{APP_ID}}/config/"
