---
- name: Configuring wireshark...
  file:
    path: "/home/showen/.var/app/{{APP_ID}}/config/wireshark/"
    state: absent

- name:
  file:
    path: "/home/showen/.var/app/{{APP_ID}}/config/wireshark/"
    state: directory
- name:
  unarchive:
    src: /home/showen/kubuntu-build/roles/setup/applications/wireshark/files/wireshark.tar.xz
    dest: "/home/showen/.var/app/{{APP_ID}}/config/"
