---
# tasks file for zed
- name: Configuring zed...
  file:
    path: "{{target_home_dir}}/.var/app/{{APP_ID}}/config/zed/"
    state: absent
- name:
  file:
    path: "{{target_home_dir}}/.var/app/{{APP_ID}}/config/zed/"
    state: directory
- name:
  unarchive:
    src: "{{target_home_dir}}/kubuntu-build/roles/setup/applications/zed/files/zed.tar.xz"
    dest: "{{target_home_dir}}/.var/app/{{APP_ID}}/config/"
