---
- name: Initializing Flatpak repository...
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Installing Applications [FLATPAK]...
  community.general.flatpak:
    name: "{{ item }}"
    remote: flathub
    state: present
  loop: "{{ FLATPAKS }}"
