---
- name: Backing up 'kubuntu-build' to GitHub...
  git_config:
    name: user.email
    value: "showenotto@proton.me"
    scope: global
- name:
  shell: "git add . && git commit -m '1.0' && git push"
  args:
    chdir: "{{target_home_dir}}/kubuntu-build/"
