---
PACKAGES:
  [
    "zsh",
    "zsh-autosuggestions",
    "vim",
    "tmux",
    "tree",
    "xclip",
    "gparted",
    "btop",
    "gnome-clocks",
    "kalk",
    "imagemagick",
    "texlive",
  ]
