---
- name: Backing up zed...
  archive:
    path: "/.var/app/{{ APP_ID }}/config/zed"
    dest: "/home/showen/kubunt-build/roles/backup/zed/files/zed.tar.xz"
    format: xz
    excludes:
      - "*.log"
      - "tmp/*"
      - "tmp"
  register: config_archive_result
